baseurl: /reis-mahnic/

collections:
  games:
    output: true
  software:
    output: true

permalink: pretty
    
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ""
      type: "games"
    values:
      layout: "subpage"
      order: 0
      home_anchor: '#game-projects'
  - scope:
      path: ""
      type: "software"
    values:
      layout: "subpage"
      order: 0
      home_anchor: '#software-development-projects'

sass:
  sass_dir: assets/css
  style: compressed

plugins:
- jekyll-autoprefixer
  